// docs.js — texto de hover, en el mismo lenguaje que el diseño (español).
// Se busca primero por nombre cualificado ("WSON.listen") y si no hay
// coincidencia, por el nombre simple ("listen" -> nada, "reactive" -> sí).

const KEYWORD_DOCS = {
	reactive: "Variable reactiva. Cualquier interpolación `{}` o bloque `if`/`for` que dependa de ella se actualiza solo cuando cambia, sin virtual DOM — solo el nodo afectado.",
	var: "Variable normal (no reactiva). Tipado opcional: `var Tipo nombre = valor`.",
	const: "Valor constante, inmutable de verdad.",
	style: "Bloque de estilos CSS. Cada `-> propiedad: valor` es una línea CSS literal; el nombre del `style` es literalmente su clase CSS — `class={nombre}` no necesita ningún lookup.",
	visual: "Bloque de plantilla HTML. Si el fichero llama a `Visual.render(...)` es una página; si no, es un componente/librería pensado para importarse.",
	watch: "Se ejecuta cada vez que cambia la reactive que observa. En un `.wsb`, se dispara con cada petición entrante que coincide con el `WSON.listen()` asignado a esa reactive.",
	useRoute: "Declara la llamada al servidor para una ruta GET desde el cliente (renderizar un visual con parámetros de ruta).",
	params: "Parámetros de ruta (`:id`). Dentro de un handler de `WSON.listen()`, usa `WSON.params()` en su lugar.",
	query: "Query string de la URL. Dentro de un handler de `WSON.listen()`, usa `WSON.query()` en su lugar.",
	import: "Importa declaraciones con nombre desde otro fichero (`.wsf`, `.wsb`, `.ws` o `.wson`).",
	export: "Marca una declaración como disponible para `import` desde otro fichero.",
	if: "Condicional dentro de una plantilla o un `watch()`. El bloque se re-renderiza solo en su posición cuando cambia la reactive de la que depende.",
	else: "Rama alternativa de un `if`.",
	for: "Itera una lista. Hace diffing por clave: reutiliza nodos DOM existentes en vez de reconstruir todo en cada cambio.",
	in: "Se usa dentro de `for (item in lista)`.",
	string: "Tipo primitivo: texto.",
	integer: "Tipo primitivo: número entero.",
	decimal: "Tipo primitivo: número con decimales.",
	boolean: "Tipo primitivo: verdadero/falso.",
	object: "Objeto anidado — sus subcampos se declaran indentados debajo, sin necesidad de más palabra clave.",
	any: "Tipo comodín, sin restricción de esquema — típico en `reactive any x = WSON.listen(...)`.",
	WSON: "Clase núcleo para mensajería estructurada: firma HMAC, cifrado AES-256-GCM, envío por HTTP entre sistemas.",
	Visual: "Clase núcleo del renderizado (SSR/SSG incluido). `Visual.render(visual)` monta la app — solo puede llamarse una vez por frontal.",
	"WSON.listen": "Registra un punto de entrada de tráfico, comparando `to`/`via` con cada petición entrante. Se asigna a una `reactive`; el procesamiento real va en su `watch()`.",
	"WSON.send": "Firma (si hay `secret`) y cifra (si `encrypt: true`) antes de enviar. Dentro del `watch()` de un `listen()`, responder con `WSON.send()` contesta la petición entrante en vez de mandar una llamada saliente nueva.",
	"WSON.enqueue": "Envío fire-and-forget: reintentos con backoff exponencial, dead letter si se agotan.",
	"WSON.showContent": "Descifra el content. Devuelve el mensaje tal cual si no estaba cifrado, o `null` si falla la clave o hubo manipulación.",
	"WSON.verify": "Verifica la firma HMAC de un WSON recibido, en tiempo constante (`crypto.timingSafeEqual`).",
	"WSON.parse": "Punto de entrada único en el receptor: verifica firma, descifra si hacía falta, expone `from`/`id`/`content`/`signatureValid`.",
	"WSON.query": "Query string dentro de un handler de `WSON.listen()`.",
	"WSON.params": "Parámetros de ruta dentro de un handler de `WSON.listen()` — cualquier segmento `:algo` es comodín a efectos de matching.",
	"WSON.getSignature": "Atajo para extraer la cabecera de firma sin leerla a mano.",
	"WSON.getTimestamp": "Atajo para extraer la cabecera de marca de tiempo sin leerla a mano.",
	to: "Endpoint (+ params de ruta) del WSON. Es un destino real: al enviar con `.send()`, viaja ahí de verdad — por eso puede disparar tu propio `listen()` si coincide.",
	via: "Method del WSON: POST, PUT o DELETE (GET se maneja aparte, ejecutando el script tal cual).",
	from: "Quién manda el WSON.",
	content: "El payload del WSON. En un `.wson`, es el esquema de tipos; en una instancia real, son los datos ya rellenos.",
	secret: "Clave para firmar (HMAC-SHA256). Solo permitido en WSON de servidor — rechazado en compilación si aparece en uno de cliente.",
	encrypt: "Si es `true`, cifra el content con AES-256-GCM (autenticado). Requiere `secret`.",
	id: "Id de correlación. Se autogenera en formato UUID al hacer `.send()`, antes de cifrar. Solo lectura.",
	createdAt: "Se autogenera igual que `id`, en el momento de `.send()`. Solo lectura.",
	httpCode: "Código de estado HTTP de la respuesta. Opcional; 200 por defecto si no se informa. Viaja fuera del bloque cifrado (no es confidencial).",
	props: "Objeto con los atributos que le pasó el componente padre a este `visual` (`<contador item={item} />` → `props.item` aquí dentro). No hay estado local por instancia: el estado que necesite sobrevivir por elemento va dentro del propio dato pasado como prop.",
	slot: "Marcador (`<slot />`) donde se inserta el contenido que el que usa este componente puso entre sus etiquetas de apertura y cierre.",
};

module.exports = { KEYWORD_DOCS };
